name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List and Read file 
          run: |
            echo "My first Github Action Job"
            ls -ltra
            cat README.md

        - name: Genate ASCII Artwork
          run: cowsay -f deragon "Run for cover, I an  DRAGON....RAWR" >> dragon.txt

       # - name: List files
       #  run: ls

        #- name: Read file
         # run: cat README.md
   